import { images } from "./assets/images";

export const description = [
  "cascada",
  "tria",
  "et toca",
  "li toca a les noies",
  "el déu del dit",
  "li toca als nois",
  "al cel",
  "tria un company",
  "hora de memoritzar",
  "la llista",
  "la norma",
  "el fantasma",
  "el rei",
  "cascada",
  "tria",
  "et toca",
  "li toca a les noies",
  "el déu del dit",
  "li toca als nois",
  "al cel",
  "tria un company",
  "hora de memoritzar",
  "la llista",
  "la norma",
  "el fantasma",
  "el rei",
  "cascada",
  "tria",
  "et toca",
  "li toca a les noies",
  "el déu del dit",
  "li toca als nois",
  "al cel",
  "tria un company",
  "hora de memoritzar",
  "la llista",
  "la norma",
  "el fantasma",
  "el rei",
  "cascada",
  "tria",
  "et toca",
  "li toca a les noies",
  "el déu del dit",
  "li toca als nois",
  "al cel",
  "tria un company",
  "hora de memoritzar",
  "la llista",
  "la norma",
  "el fantasma",
  "el rei",
  "cascada",
  "tria",
  "et toca",
  "li toca a les noies",
  "el déu del dit",
  "li toca als nois",
  "al cel",
  "tria un company",
  "hora de memoritzar",
  "la llista",
  "la norma",
  "el fantasma",
  "el rei",
];

export const cards = [
  images.card0,
  images.card1,
  images.card2,
  images.card3,
  images.card4,
  images.card5,
  images.card6,
  images.card7,
  images.card8,
  images.card9,
  images.card11,
  images.card12,
  images.card13,
  images.card14,
  images.card15,
  images.card16,
  images.card17,
  images.card18,
  images.card19,
  images.card20,
  images.card21,
  images.card22,
  images.card23,
  images.card24,
  images.card25,
  images.card26,
  images.card27,
  images.card28,
  images.card29,
  images.card30,
  images.card31,
  images.card32,
  images.card33,
  images.card34,
  images.card35,
  images.card36,
  images.card37,
  images.card38,
  images.card39,
  images.card40,
  images.card41,
  images.card42,
  images.card43,
  images.card44,
  images.card45,
  images.card46,
  images.card47,
  images.card48,
  images.card49,
  images.card50,
  images.card51,
];
